## Early EDA

In [1]:
import pandas as pd
import numpy as np

In [35]:
nrows_to_read = 20000  # Adjust the number of rows to read since data is too big atm
movies = pd.read_csv("data/movie_data.csv", nrows=nrows_to_read)

In [36]:
movies

,_id,genres,image_url,imdb_id,imdb_link,movie_id,movie_title,original_language,overview,popularity,production_countries,release_date,runtime,spoken_languages,tmdb_id,tmdb_link,vote_average,vote_count,year_released
0,5fc85f606758f69634496fd3,"[""Music"",""Animation""]",film-poster/4/6/4/4/4/0/464440-football-freaks...,NaN,NaN,football-freaks,Football Freaks,en,"Football crazy, football mad. Don’t watch this...",0.600,"[""United Kingdom""]",1971-12-05,0.0,[],535272.0,https://www.themoviedb.org/movie/535272/,0.0,0.0,1971.0
1,5fc85ff26758f696344ace0c,[],film-poster/2/4/5/5/0/0/245500-aftermath-0-230...,tt0586129,http://www.imdb.com/title/tt0586129/maindetails,aftermath-1960,Aftermath,en,Aftermath was the pilot for an unsold TV serie...,0.600,[],1960-04-17,22.0,[],318331.0,https://www.themoviedb.org/movie/318331/,8.0,1.0,1960.0
2,5fc85f606758f69634496fcd,"[""Drama""]",film-poster/9/3/3/1/8/93318-where-chimneys-are...,tt0045731,http://www.imdb.com/title/tt0045731/maindetails,where-chimneys-are-seen,Where Chimneys Are Seen,ja,Gosho’s most celebrated film both in Japan and...,1.568,"[""Japan""]",1953-03-05,108.0,"[""日本語""]",117779.0,https://www.themoviedb.org/movie/117779/,6.6,10.0,1953.0
3,5fc85f606758f69634496fd1,"[""Drama""]",NaN,tt0187327,http://www.imdb.com/title/tt0187327/maindetails,the-musicians-daughter,The Musician's Daughter,en,Carl Wagner's good wife was dying. His heart b...,0.600,"[""United States of America""]",1911-12-12,15.0,[],560377.0,https://www.themoviedb.org/movie/560377/,0.0,0.0,1911.0
4,5fc85f606758f69634496fd4,"[""Documentary""]",film-poster/4/5/4/6/0/3/454603-50-years-of-fab...,tt4769914,http://www.imdb.com/title/tt4769914/maindetails,50-years-of-fabulous,50 Years of Fabulous,en,50 Years of Fabulous recounts the rich history...,0.600,[],2018-05-17,75.0,[],525187.0,https://www.themoviedb.org/movie/525187/,0.0,0.0,2018.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,5fc86ac56758f696347bb816,[],film-poster/7/1/0/2/9/71029-mudvayne-rock-am-r...,NaN,NaN,mudvayne-rock-am-ring-2001,Mudvayne: Rock Am Ring 2001,en,Dig,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19996,5fc86ac56758f696347bb816,[],film-poster/7/1/0/2/9/71029-mudvayne-rock-am-r...,NaN,NaN,mudvayne-rock-am-ring-2001,Mudvayne: Rock Am Ring 2001,en,Dig,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19997,5fc86ac56758f696347bb816,[],film-poster/7/1/0/2/9/71029-mudvayne-rock-am-r...,NaN,NaN,mudvayne-rock-am-ring-2001,Mudvayne: Rock Am Ring 2001,en,Dig,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19998,5fc86ac56758f696347bb816,[],film-poster/7/1/0/2/9/71029-mudvayne-rock-am-r...,NaN,NaN,mudvayne-rock-am-ring-2001,Mudvayne: Rock Am Ring 2001,en,Dig,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19999,5fc86ac56758f696347bb816,[],film-poster/7/1/0/2/9/71029-mudvayne-rock-am-r...,NaN,NaN,mudvayne-rock-am-ring-2001,Mudvayne: Rock Am Ring 2001,en,Dig,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
ratings_df = pd.read_csv("data/ratings_export.csv")

In [19]:
ratings_df

,_id,movie_id,rating_val,user_id
0,5fc57c5d6758f6963451a07f,feast-2014,7,deathproof
1,5fc57c5d6758f6963451a063,loving-2016,7,deathproof
2,5fc57c5d6758f6963451a0ef,scripted-content,7,deathproof
3,5fc57c5d6758f6963451a060,the-future,4,deathproof
4,5fc57c5c6758f69634519398,mank,5,deathproof
...,...,...,...,...
11078162,6239f4f1a936b95600b3d798,alien-3,6,turnitip
11078163,6239f4f1a936b95600b3d799,battleship-potemkin,7,turnitip
11078164,6239f4f1a936b95600b3d79e,pusher,6,turnitip
11078165,6239f4f1a936b95600b3d7a1,wild-strawberries,7,turnitip
11078166,6239f4f1a936b95600b3d7a2,x-2022,5,turnitip

In [5]:
users_df = pd.read_csv("data/users_export.csv")

users_df

,_id,display_name,num_ratings_pages,num_reviews,username
0,5fc4172ec6cd28ebd99dd0e2,Lucy,32.0,1650,deathproof
1,5fc4172ec6cd28ebd99dd0ea,Matt Singer,52.0,1915,superpulse
2,5fc4172ec6cd28ebd99dd0ed,Sean Baker,21.0,1283,lilfilm
3,5fc4172ec6cd28ebd99dd0ee,iana,37.0,1177,ianamurray
4,5fc419171ebf67b9fbe48615,Lizzy,57.0,1810,punchdrunklizzy
...,...,...,...,...,...
8134,6239b430a936b956009c993c,Máté Turi-Mészáros,NaN,237,mateazember
8135,6239cbf7a936b95600a2d24c,Finn,NaN,297,finnvor1
8136,6239d254a936b95600a4472f,Daniel,NaN,1231,daniel
8137,6239df37a936b95600aa7aa5,ButterflyFilms,NaN,800,butterflyfilms
8138,6239e55ba936b95600ae2012,Flo,NaN,1901,poellnerson